french_phoneme_practice_different_phonemes = {
    "chat": "ʃa",  # (cat)
    "pomme": "pɔm",  # (apple)
    "fleur": "flœʁ",  # (flower)
    "soleil": "sɔlɛj",  # (sun)
    "bonjour": "bɔ̃ʒuʁ",  # (good morning)
    "merci": "mɛʁsi",  # (thank you)
    "frais": "fʁɛ",  # (fresh)
    "voiture": "vwatyʁ",  # (car)
    "manger": "mɑ̃ʒe",  # (to eat)
    "plage": "plaʒ",  # (beach)
    "belle": "bɛl",  # (beautiful)
    "livre": "livʁ",  # (book)
    "fenêtre": "f(ə)nɛtʁ",  # (window)
    "sourire": "suʁiʁ",  # (to smile)
    "chocolat": "ʃɔkɔla",  # (chocolate)
    "café": "kafe",  # (coffee)
    "amour": "amuʁ",  # (love)
    "école": "ekɔl",  # (school)
    "oiseau": "wazo",  # (bird)
    "rose": "ʁoz",  # (rose)
}

french_words_ipa_increasing_difficulty = {
    "chien": "ʃjɛ̃",  # (dog)
    "chat": "ʃa",  # (cat)
    "soleil": "sɔlɛj",  # (sun)
    "fleur": "flœʁ",  # (flower)
    "merci": "mɛʁsi",  # (thank you)
    "bonjour": "bɔ̃ʒuʁ",  # (good morning)
    "pomme": "pɔm",  # (apple)
    "croissant": "kʁwasɑ̃",  # (croissant)
    "plaisir": "plɛziʁ",  # (pleasure)
    "prononciation": "pʁɔnɔ̃sjasjɔ̃",  # (pronunciation)
    "phénomène": "fenɔmɛn",  # (phenomenon)
    "sécurité": "sekyʁite",  # (security)
    "révolution": "ʁevɔlysjɔ̃",  # (revolution)
    "pharmacie": "faʁmasi",  # (pharmacy)
    "xylophone": "ksilɔfɔn",  # (xylophone)
    "rhinocéros": "ʁinɔseʁɔs",  # (rhinoceros)
    "exacerbation": "ɛgzaseʁbasjɔ̃",  # (exacerbation)
    "incompréhensibilité": "ɛ̃kɔ̃pʁeɑ̃sibilite",  # (incomprehensibility)
    "anticonstitutionnellement": "ɑ̃tikɔ̃stitysjɔnɛlmɑ̃",  # (unconstitutionally)
}